
package com.mymeteo.webservices.meteo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeteoService", targetNamespace = "http://www.mymeteo.com/webservices/meteo", wsdlLocation = "file:/home/david/Workspace/workspace-epsi/ws-bookmarks/src/main/wsdl/meteo.wsdl")
public class MeteoService_Service
    extends Service
{

    private final static URL METEOSERVICE_WSDL_LOCATION;
    private final static WebServiceException METEOSERVICE_EXCEPTION;
    private final static QName METEOSERVICE_QNAME = new QName("http://www.mymeteo.com/webservices/meteo", "MeteoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/david/Workspace/workspace-epsi/ws-bookmarks/src/main/wsdl/meteo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METEOSERVICE_WSDL_LOCATION = url;
        METEOSERVICE_EXCEPTION = e;
    }

    public MeteoService_Service() {
        super(__getWsdlLocation(), METEOSERVICE_QNAME);
    }

    public MeteoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), METEOSERVICE_QNAME, features);
    }

    public MeteoService_Service(URL wsdlLocation) {
        super(wsdlLocation, METEOSERVICE_QNAME);
    }

    public MeteoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METEOSERVICE_QNAME, features);
    }

    public MeteoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeteoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeteoService
     */
    @WebEndpoint(name = "MeteoServicePort")
    public MeteoService getMeteoServicePort() {
        return super.getPort(new QName("http://www.mymeteo.com/webservices/meteo", "MeteoServicePort"), MeteoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeteoService
     */
    @WebEndpoint(name = "MeteoServicePort")
    public MeteoService getMeteoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mymeteo.com/webservices/meteo", "MeteoServicePort"), MeteoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METEOSERVICE_EXCEPTION!= null) {
            throw METEOSERVICE_EXCEPTION;
        }
        return METEOSERVICE_WSDL_LOCATION;
    }

}
