
package com.mymeteo.webservices.meteo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.mymeteo.meteo.Lieu;
import com.mymeteo.meteo.ObjectFactory;
import com.mymeteo.meteo.Releve;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeteoService", targetNamespace = "http://www.mymeteo.com/webservices/meteo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeteoService {


    /**
     * 
     * @param partLieu
     * @return
     *     returns com.mymeteo.meteo.Releve
     */
    @WebMethod
    @WebResult(name = "releve", targetNamespace = "http://www.mymeteo.com/meteo", partName = "partReleve")
    @Action(input = "http://www.mymeteo.com/webservices/meteo/MeteoService/releveMeteoRequest", output = "http://www.mymeteo.com/webservices/meteo/MeteoService/releveMeteoResponse")
    public Releve releveMeteo(
        @WebParam(name = "lieu", targetNamespace = "http://www.mymeteo.com/meteo", partName = "partLieu")
        Lieu partLieu);

}
